---
# defaults file for nginx

# Napa_Labs block:

nginx_binary_url: "https://example.com/registry/nginx_1.0.0"
nginx_user: "nginx"
nginx_conf_dir: "/etc/nginx"

### end

nginx_http_port: 80
nginx_https_ports: ['443', 'ssl', 'http2']

nginx_virtualhosts:
  available: /etc/nginx/sites-available
  enabled: /etc/nginx/sites-enabled
  hosts:
    - name: "web-1"
      server_name: "web-1.example.com"
      root: "/var/www/web-1"
    - name: "web-2"
      server_name: "web-2.example.com"
      root: "/var/www/web-2"

virtualhosts_files: ['index', 'index.html', 'index.htm', 'index.nginx-debian.html']

nginx_conf:
  worker_connections: "2048"
  sendfile: "on"
  tcp_nodelay: "on"
  tcp_nopush: "on"

