---
# - name: Run tasks for Debian OS Family
#   ansible.builtin.include_tasks: "Debian.yaml"
#   when: ansible_os_family == 'Debian'

# - name: Run tasks for RedHat OS Family
#   ansible.builtin.include_tasks: "RedHat.yaml"
#   when: ansible_os_family == 'RedHat'

- name: Ensure nginx user exists
  user:
    name: "{{ nginx_user }}"
    state: present

- name: Ensure NGINX_CONF_DIR exists
  file:
    path: "{{ nginx_conf_dir }}"
    state: directory
    owner: "{{ nginx_user }}"
    mode: '0700'

- name: Copy nginx unit template
  template:
    src: "nginx.service.j2"
    dest: "/etc/systemd/system/nginx.service"
    owner: root
    group: root
    mode: '0644'

- name: Download and install nginx binary
  get_url:
    url: "{{ nginx_binary_url }}"
    dest: "/bin/nginx"
    mode: '0755'
    owner: "{{ nginx_user }}"

- name: Copy nginx config templates
  template:
    src: "{{ item }}"
    dest: "{{ nginx_conf_dir }}"
    owner: "{{ nginx_user }}"
    mode: '0600'
  with_fileglob:
    - "templates/nginx/*"
  notify: Reload the Nginx service